http:
  host: "localhost"
  port: "8081"
  
file:
  readPath: "C:\\Users\\Rajesh\\AnypointStudio\\studio-workspace\\mulesoft-components\\src\\main\\resources\\sample-data\\"
  writePath : "C:\\Users\\Rajesh\\AnypointStudio\\studio-workspace\\mulesoft-components\\src\\main\\resources\\output\\"  